name: Digger Plan

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  issue_comment:
    types:
      - created
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pull-requests: write
      statuses: write
      issues: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Digger run (plan/no-backend)
        uses: diggerhq/digger@vLatest
        with:
          digger-spec: ${{ toJson(github) }}
          setup-terraform: true
          no-backend: true
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
