name: Digger Plan

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pull-requests: write
      statuses: write
      issues: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (optional) quick visibility
      - name: Show repo layout
        run: |
          ls -lah .
          ls -lah terraform || true

      - name: Digger run (backendless, plan-only)
        uses: diggerhq/digger@vLatest
        with:
          # run without orchestrator; parse PR events directly
          no-backend: true

          # Install Terraform for you (pin if you like)
          setup-terraform: true
          terraform-version: 1.5.7

          # We’re not setting up any cloud (AWS/GCP/Azure) on purpose
          # to avoid credential requirements during this POC.
          # If you later want locks without an orchestrator, re-enable pr_locks
          # and supply the appropriate cloud setup inputs.

          # Keep default checkout behavior
          configure-checkout: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
