name: Digger Plan (debug)

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  issue_comment:
    types:
      - created
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pull-requests: write
      statuses: write
      issues: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dump env & directory
        run: |
          echo "=== ROOT FILES ==="
          ls -lah .
          echo "=== terraform dir ==="
          ls -lah terraform || echo "terraform missing"

      - name: Digger run (plan / no-backend)
        uses: diggerhq/digger@vLatest
        with:
          digger-spec: ${{ toJson(github) }}
          setup-terraform: true
          terraform-version: 1.5.7
          no-backend: true
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check CLI presence
        run: |
          if command -v digger; then
            echo "Digger CLI present"
            digger version || true
          else
            echo "Digger CLI missing"
            exit 1
          fi
